name: ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: latest
      - run: git clone --depth 1 https://github.com/kotoba-lang/org-synopsys-liberty ../org-synopsys-liberty
      - run: git clone --depth 1 https://github.com/kotoba-lang/org-si2-lef ../org-si2-lef
      - run: clojure -M:test
      - run: clojure -M:lint
